In [1]:
POO_UP  = [{1,2,3,4,5,6,7,8,9,10}
           ,[11,12,13,14,15,16,17,18,19,20]
           ,[21,22,23,24,25,26,27,28,29,30]
           ,[31,32,33,34,35,36,37,38,39,40]
           ,[41,42,43,44,45,46,47,48,49,50]
           ,[51,52,53,54,55,56,57,58,59,60]
           ,[61,62,63,64,65,66,67,68,69,70]
           ,[71,72,73,74,75,76,77,78,79,80]
           ,[81,82,83,84,85,86,87,88,89,90]
           ,[91,92,93,94,95,96,97,98,99,100]]

In [2]:
print(POO_UP)

[{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}, [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40], [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], [51, 52, 53, 54, 55, 56, 57, 58, 59, 60], [61, 62, 63, 64, 65, 66, 67, 68, 69, 70], [71, 72, 73, 74, 75, 76, 77, 78, 79, 80], [81, 82, 83, 84, 85, 86, 87, 88, 89, 90], [91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]

In [4]:
import pandas as pd

In [6]:
numeros = pd.DataFrame(POO_UP)

In [7]:
numeros

    0   1   2   3   4   5   6   7   8    9
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100